enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - checksum: de061cd3caf72888721b532ca81faa1747e430de25f2f71ccfea247f5050f3e8979bbece6702560834b0c2d54566b023235da71101bf53f8a85e86f8c27cb582
    path: .yarn/plugins/@yarnpkg/plugin-deployer.cjs
    spec: packages/yarn-plugin-deployer/bundles/@yarnpkg/plugin-deployer.js

pnpEnableEsmLoader: true

preferReuse: true

tsEnableAutoTypes: false
