enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - checksum: 969a0fe6b4254ffe62955b61a7502733a0cc66c6fe1892a1e0e6e04d761d4e652e23dcb1bb734e1b7ae37715b9992220624ea5d1b4eebafeb1823a37da843002
    path: .yarn/plugins/@yarnpkg/plugin-deployer.cjs
    spec: packages/yarn-plugin-deployer/bundles/@yarnpkg/plugin-deployer.js

pnpEnableEsmLoader: true

preferReuse: true

tsEnableAutoTypes: false
