name: "yarn setup"
description: "yarn setup"
runs:
  using: "composite"
  steps:
    - run: |
        corepack enable
        corepack prepare --activate
      shell: bash
    - id: yarn-cache-dir
      run: echo "YARN_CACHE_DIR=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      shell: bash
    - id: yarn-cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.yarn-cache-dir.outputs.YARN_CACHE_DIR }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        save-always: true
    - run: |
        CACHE_HIT="${{ steps.yarn-cache.outputs.cache-hit }}"
        NODE_MODULES_EXISTS=$(test -d "node_modules" && echo "true" || echo "false")
        if [[ "$CACHE_HIT" != 'true' || "$NODE_MODULES_EXISTS" == 'false' ]]; then
          yarn install
        fi
      shell: bash
