name: cd
on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip cd]')"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: ./.github/actions/node-setup
      - uses: ./.github/actions/yarn-setup
      - run: yarn workspaces foreach -p --include="seokju.me" --since=$(git rev-parse HEAD~1) run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_CF_KV_ARN: ${{ secrets.AWS_CF_KV_ARN }}
